notifications:
  email: false
language: python
python:
  - '3.6'
cache: pip
before_install:
  - pip install poetry codecov
install:
  - poetry install
script:
  - poetry run coverage run -m pytest -v
after_success:
  - codecov
deploy:
  provider: script
  script: poetry config pypi-token.pypi "${POETRY_PYPI_TOKEN_PYPI}" && poetry publish --no-interaction --build
  on:
    tags: true
    branch: master
    python: '3.6'
  allow_failure: false
